# Generated by Django 4.2.3 on 2023-10-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
