# Generated by Django 4.2.3 on 2023-10-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gallery', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
